import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTblMedicalPracticeM1690163573967
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TABLE \`medical_practice_m\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`change_category\` int DEFAULT NULL,
        \`master_type\` varchar(1)  DEFAULT NULL,
        \`medical_practice_code\` int NOT NULL UNIQUE,
        \`significant_digits_1\` int DEFAULT NULL,
        \`abbreviated_kanji\` varchar(64)  DEFAULT NULL,
        \`significant_digits_2\` int DEFAULT NULL,
        \`abbreviated_kana\` varchar(20)  DEFAULT NULL,
        \`data_standard_code\` VARCHAR(6) DEFAULT NULL,
        \`significant_digits_3\` int DEFAULT NULL,
        \`kanji_name_1\` varchar(12)  DEFAULT NULL,
        \`score_identification_1\` int DEFAULT NULL,
        \`new_current_number\` int DEFAULT NULL,
        \`domestic_external_application_category\` int DEFAULT NULL,
        \`application_category\` int DEFAULT NULL,
        \`out_of_hospital\` int DEFAULT NULL,
        \`comprehensive_inspection\` int DEFAULT NULL,
        \`spare\` int DEFAULT NULL,
        \`dpc_application_category\` int DEFAULT NULL,
        \`hospital_classification\` int DEFAULT NULL,
        \`addition_1\` int DEFAULT NULL,
        \`target_category_1\` int DEFAULT NULL,
        \`addition_2\` int DEFAULT NULL,
        \`anesthesia_identification\` int DEFAULT NULL,
        \`addition_division_1\` int DEFAULT NULL,
        \`injury_name_related_category\` int DEFAULT NULL,
        \`medical_management_fee\` int DEFAULT NULL,
        \`actual_number_of_days\` int DEFAULT NULL,
        \`number_of_days_number\` int DEFAULT NULL,
        \`pharmaceutical_category\` int DEFAULT NULL,
        \`increment_value_identification\` int DEFAULT NULL,
        \`lower_limit\` int DEFAULT NULL,
        \`upper_limit\` int DEFAULT NULL,
        \`increment_value\` int DEFAULT NULL,
        \`increment_score\` int DEFAULT NULL,
        \`upper_and_lower_limit_error_handling\` int DEFAULT NULL,
        \`maximum_number_of_times\` int DEFAULT NULL,
        \`upper_limit_error_handling\` int DEFAULT NULL,
        \`note_addition_code\` int DEFAULT NULL,
        \`note_addition_serial_number\` varchar(1)  DEFAULT NULL,
        \`general_age\` int DEFAULT NULL,
        \`minimum_age\` varchar(2)  DEFAULT NULL,
        \`upper_age_limit\` varchar(2)  DEFAULT NULL,
        \`addition_division_2\` int DEFAULT NULL,
        \`conformity_division\` int DEFAULT NULL,
        \`target_facility_standard\` int DEFAULT NULL,
        \`addition_division_3\` int DEFAULT NULL,
        \`addition_division_4\` int DEFAULT NULL,
        \`object_identification\` int DEFAULT NULL,
        \`aggregation_classification_for_donors\` int DEFAULT NULL,
        \`inspection_division\` int DEFAULT NULL,
        \`inspection_implementation_group_classification\` int DEFAULT NULL,
        \`target_category_2\` int DEFAULT NULL,
        \`addition_division_5\` int DEFAULT NULL,
        \`addition_division_6\` int DEFAULT NULL,
        \`addition_division_7\` int DEFAULT NULL,
        \`addition_division_8\` int DEFAULT NULL,
        \`score_identification_2\` int DEFAULT NULL,
        \`old_score\` int DEFAULT NULL,
        \`kanji_name_change_category\` int DEFAULT NULL,
        \`kana_name_change_category\` int DEFAULT NULL,
        \`specimen_test_comment\` int DEFAULT NULL,
        \`target_category_3\` int DEFAULT NULL,
        \`comprehensive_declining_category\` int DEFAULT NULL,
        \`addition_division_9\` int DEFAULT NULL,
        \`spare_3\` int DEFAULT NULL,
        \`identification_hospitalization\` int DEFAULT NULL,
        \`addition_division_10\` int DEFAULT NULL,
        \`notice_identification_division_1\` int DEFAULT NULL,
        \`notice_identification_division_2\` int DEFAULT NULL,
        \`regional_addition\` int DEFAULT NULL,
        \`bed_number_classification\` int DEFAULT NULL,
        \`facility_standard_1\` int DEFAULT NULL,
        \`facility_standard_2\` int DEFAULT NULL,
        \`facility_standard_3\` int DEFAULT NULL,
        \`facility_standard_4\` int DEFAULT NULL,
        \`facility_standard_5\` int DEFAULT NULL,
        \`facility_standard_6\` int DEFAULT NULL,
        \`facility_standard_7\` int DEFAULT NULL,
        \`facility_standard_8\` int DEFAULT NULL,
        \`facility_standard_9\` int DEFAULT NULL,
        \`facility_standard_10\` int DEFAULT NULL,
        \`addition_section_11\` int DEFAULT NULL,
        \`stay_surgery\` int DEFAULT NULL,
        \`dental_division\` int DEFAULT NULL,
        \`a_for_code_table\` varchar(1)  DEFAULT NULL,
        \`notification_a\` varchar(1)  DEFAULT NULL,
        \`date_of_change\` int DEFAULT NULL,
        \`abolition_date\` int DEFAULT NULL,
        \`sequence_number\` int DEFAULT NULL,
        \`chapter_1\` int DEFAULT NULL,
        \`part_1\` int DEFAULT NULL,
        \`division_number_1\` int DEFAULT NULL,
        \`branch_number_1\` int DEFAULT NULL,
        \`item_number_1\` int DEFAULT NULL,
        \`chapter_2\` int DEFAULT NULL,
        \`part_2\` int DEFAULT NULL,
        \`division_number_2\` int DEFAULT NULL,
        \`branch_number_2\` int DEFAULT NULL,
        \`item_no_2\` int DEFAULT NULL,
        \`minimum_age_1\` int DEFAULT NULL,
        \`maximum_age_1\` varchar(2)  DEFAULT NULL,
        \`medical_practice_code_1\` int DEFAULT NULL,
        \`minimum_age_2\` varchar(2)  DEFAULT NULL,
        \`maximum_age_2\` varchar(2)  DEFAULT NULL,
        \`medical_practice_code_2\` int DEFAULT NULL,
        \`minimum_age_3\` varchar(2)  DEFAULT NULL,
        \`maximum_age_3\` varchar(2)  DEFAULT NULL,
        \`medical_practice_code_3\` int DEFAULT NULL,
        \`minimum_age_4\` varchar(2)  DEFAULT NULL,
        \`maximum_age_4\` varchar(2)  DEFAULT NULL,
        \`medical_practice_code_4\` int DEFAULT NULL,
        \`transfer\` int DEFAULT NULL,
        \`kanji_name_2\` varchar(128)  DEFAULT NULL,
        \`addition_3\` varchar(1)  DEFAULT NULL,
        \`addition_4\` varchar(1)  DEFAULT NULL,
        \`addition_5\` varchar(1)  DEFAULT NULL,
        \`division_number_3\` varchar(30)  DEFAULT NULL,
        \`monitoring\` varchar(1)  DEFAULT NULL,
        \`addition_6\` varchar(1)  DEFAULT NULL,
        \`spare_1\` int DEFAULT NULL,
        \`spare_2\` int DEFAULT NULL,
        \`reserve_3\` int DEFAULT NULL,
        \`created_date\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        \`update_date\` datetime DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (\`id\`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS mf_t;`);
  }
}
